[package]
name = "live-game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
color-eyre = "0.6.2"
crossterm = "0.27.0"
ratatui = "0.26.1"
itertools = "0.12.1"
log = "0.4.21"
rand = "0.8.5"
clap = { version = "4.5.2", features = ["derive"] }
